export const movieNames = [
  "Memento",
  "Inception",
  "Interstellar",
  "The Prestige",
  "The Dark Knight",
  "Fight Club",
  "Pulp Fiction",
  "The Shawshank Redemption",
  "Goodfellas",
  "The Godfather",
  "The Matrix",
  "The Silence of the Lambs",
  "Seven",
  "The Departed",
  "Gladiator",
  "Braveheart",
  "Titanic",
  "Forrest Gump",
  "Schindler's List",
  "Jurassic Park",
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Lion King",
  "Star Wars: Episode IV - A New Hope",
  "Back to the Future",
  "Eternal Sunshine of the Spotless Mind",
  "The Avengers",
  "The Social Network",
  "The Great Gatsby",
  "The Revenant",
  "La La Land",
  "The Big Lebowski",
  "The Shawshank Redemption",
  "Gone with the Wind",
  "Casablanca",
  "Citizen Kane",
  "The Wizard of Oz",
  "Psycho",
  "Taxi Driver",
  "Blade Runner",
  "Reservoir Dogs",
  "Inglourious Basterds",
  "The Green Mile",
  "The Dark Knight Rises",
  "Fight Club",
  "American Beauty",
  "Avatar",
  "Deadpool",
  "The Departed",
  "The Pianist",
  "The Truman Show",
  "The Sixth Sense",
];
